.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH thud 1  "thud 0.2.0" 
.SH NAME
thud \- Generate directory thumbnails for GTK\-based file browsers from images inside them.
.SH SYNOPSIS
\fBthud\fR [\fB\-s\fR|\fB\-\-size\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIINPUT_DIRECTORY\fR> <\fIOUTPUT_FILE\fR> 
.SH DESCRIPTION
.PP
thud is a thumbnailer that generates thumbnails for directories.
thud stands for (thu)mbnail (d)irectory. It is written in Rust
with no external library dependencies.
.PP
thud can optionally be configured with a ~/.config/thud/config.toml.
By default, thud will create directory thumbnails for all directories
that have a cover.{png,jpg}. You can configure how thud creates
thumbnails with strategies.
.PP
For an example config file, see:
https://github.com/donovanglover/thud/blob/master/examples/config.toml
.PP
For a list of available strategies, see:
https://github.com/donovanglover/thud/blob/master/src/strategy.rs
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-size\fR=\fIINTEGER\fR [default: 128]
Thumbnail size
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print what thud is doing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIINPUT_DIRECTORY\fR>
Directory to thumbnail
.TP
<\fIOUTPUT_FILE\fR>
Where to save the output image
.SH VERSION
v0.2.0
.SH AUTHORS
Copyright (C) 2022\-2023 Donovan Glover <https://donovan.is/>
